version: '3.8'
services:

  mongo:
    image: mongo
    ports:
     - "27017:27017"
    volumes:
     - ./data:/data/db 
    restart: unless-stopped


  backend:
    build: 
      context: ./api   # Specify the path to the directory containing the Dockerfile
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    env_file:
      - ./api/.env
    environment:
      - MONGO_URL=mongodb://mongo:27017/Influx-main
      - DB_NAME=Influx-main
    restart: unless-stopped
    container_name: backend



  frontend:
    build: 
      context: ./main   # Specify the path to the directory containing the Dockerfile for the frontend
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    container_name: frontend


